const fs = require("node:fs");
const path = require("node:path");
const yaml = require("./minimal-build/node_modules/js-yaml");
const { minify } = require("./minimal-build/node_modules/terser");

const repoRoot = path.join(__dirname, "..");
const scriptTargets = [
  {
    core: "box",
    source: "internal/buildbox.js",
    output: "internal/buildbox.min.js",
  },
];
const targets = [
  {
    source: "internal/cores/box/box.json",
    output: "internal/cores/box/box.min.json",
    format: "json",
  },
  {
    source: "internal/cores/box/enhanced.json",
    output: "internal/cores/box/enhanced.min.json",
    format: "json",
  },
  {
    source: "internal/cores/box/minimal.json",
    output: "internal/cores/box/minimal.min.json",
    format: "json",
  },
];

const minifyJson = (source) => JSON.stringify(JSON.parse(source));

const minifyYaml = (source) =>
  yaml
    .dump(yaml.load(source), {
      flowLevel: 0,
      lineWidth: -1,
      noRefs: true,
    })
    .trimEnd();

const banner = (core) =>
  [
    "// Code generated by script/minimal.js. DO NOT EDIT.",
    `// Minified from internal/build${core}.js; run \`make minimal\` to regenerate.`,
  ].join("\n");

const minifyScripts = async () => {
  for (const target of scriptTargets) {
    const sourcePath = path.join(repoRoot, target.source);
    const outputPath = path.join(repoRoot, target.output);
    const source = fs.readFileSync(sourcePath, "utf8");
    const result = await minify(source, {
      module: true,
      compress: true,
      mangle: true,
      format: {
        comments: false,
        preamble: banner(target.core),
      },
    });
    if (result.error) throw result.error;
    fs.writeFileSync(outputPath, result.code + "\n");
    console.log(`${target.source} -> ${target.output}`);
  }
};

const minifyConfigs = () => {
  for (const target of targets) {
    const sourcePath = path.join(repoRoot, target.source);
    const outputPath = path.join(repoRoot, target.output);
    const source = fs.readFileSync(sourcePath, "utf8");
    const output =
      target.format === "json" ? minifyJson(source) : minifyYaml(source);

    fs.writeFileSync(outputPath, output);
    console.log(`${target.source} -> ${target.output}`);
  }
};

const main = async () => {
  await minifyScripts();
  minifyConfigs();
};

main().catch((err) => {
  console.error(err.message ?? err);
  process.exit(1);
});
