// Code generated by script/bundle-build. DO NOT EDIT.
// Edit the sources in internal/build/src/box/ and run `make bundle`.

// feature: location
(() => {
const locationEntries = [
  {
    cca2: "CN",
    flag: "🇨🇳",
    keywords: [
      "CN",
      "CHN",
      "BACK",
      "China",
      "中国",
      "中國",
      "回国",
      "回國",
      "国内",
      "國內",
      "华东",
      "华西",
      "华南",
      "华北",
      "华中",
      "江苏",
      "北京",
      "上海",
      "广州",
      "深圳",
      "杭州",
      "徐州",
      "青岛",
      "宁波",
      "镇江",
    ],
    area: "AREA_ASIA",
  },
  {
    cca2: "HK",
    flag: "🇭🇰",
    keywords: [
      "HK",
      "HKG",
      "HKT",
      "HKBN",
      "CMHK",
      "Smartone",
      "HKBNES",
      "HGC",
      "WTT",
      "CMI",
      "Hongkong",
      "香港",
      "Hong Kong",
      "HongKong",
      "HONG KONG",
      "深港",
      "沪港",
      "呼港",
      "穗港",
      "京港",
      "港",
    ],
    area: "AREA_ASIA",
  },
  {
    cca2: "MO",
    flag: "🇲🇴",
    keywords: ["MO", "MAC", "CTM", "Macao", "澳门", "澳門", "CTM"],
    area: "AREA_ASIA",
  },
  {
    cca2: "TW",
    flag: "🇹🇼",
    keywords: [
      "TW",
      "TWN",
      "CHT",
      "HINET",
      "ROC",
      "Taiwan",
      "台湾",
      "臺灣",
      "台灣",
      "中華民國",
      "中华民国",
      "台北",
      "台中",
      "新北",
      "彰化",
      "台",
      "臺",
      "Taipei",
      "Tai Wan",
    ],
    area: "AREA_ASIA",
  },
  {
    cca2: "JP",
    flag: "🇯🇵",
    keywords: [
      "JP",
      "JPN",
      "TYO",
      "NRT",
      "Japan",
      "日本",
      "东京",
      "大阪",
      "埼玉",
      "沪日",
      "穗日",
      "川日",
      "中日",
      "泉日",
      "杭日",
      "深日",
      "辽日",
      "广日",
      "大坂",
      "Osaka",
      "Tokyo",
    ],
    area: "AREA_ASIA",
  },
  {
    cca2: "KR",
    flag: "🇰🇷",
    keywords: [
      "KR",
      "KOR",
      "SEL",
      "Korea",
      "韩国",
      "韓國",
      "韩",
      "韓",
      "首尔",
      "春川",
      "Chuncheon",
      "Seoul",
    ],
    area: "AREA_ASIA",
  },
  {
    cca2: "VN",
    flag: "🇻🇳",
    keywords: ["VN", "VNM", "Vietnam", "越南", "胡志明"],
    area: "AREA_ASIA",
  },
  {
    cca2: "KH",
    flag: "🇰🇭",
    keywords: ["KH", "KGZ", "Cambodia", "柬埔寨"],
    area: "AREA_ASIA",
  },
  {
    cca2: "LA",
    flag: "🇱🇦",
    keywords: ["LA", "LAO", "Laos", "老挝", "老撾"],
    area: "AREA_ASIA",
  },
  {
    cca2: "TH",
    flag: "🇹🇭",
    keywords: ["TH", "THA", "Thailand", "泰国", "泰國", "曼谷", "🇹🇭"],
    area: "AREA_ASIA",
  },
  {
    cca2: "MM",
    flag: "🇲🇲",
    keywords: ["MM", "MMR", "Myanmar", "缅甸", "緬甸"],
    area: "AREA_ASIA",
  },
  {
    cca2: "MY",
    flag: "🇲🇾",
    keywords: ["MY", "MYS", "Malaysia", "马来", "馬來", "吉隆坡", "大馬"],
    area: "AREA_ASIA",
  },
  {
    cca2: "ID",
    flag: "🇮🇩",
    keywords: ["ID", "IDN", "Indonesia", "印尼", "印度尼西亚", "雅加达"],
    area: "AREA_ASIA",
  },
  {
    cca2: "SG",
    flag: "🇸🇬",
    keywords: [
      "SG",
      "SGP",
      "Singapore",
      "新加坡",
      "狮城",
      "沪新",
      "京新",
      "中新",
      "泉新",
      "穗新",
      "深新",
      "杭新",
      "广新",
      "廣新",
      "滬新",
    ],
    area: "AREA_ASIA",
  },
  {
    cca2: "PH",
    flag: "🇵🇭",
    keywords: ["PH", "PHL", "Philippines", "菲律宾", "菲律賓"],
    area: "AREA_ASIA",
  },
  {
    cca2: "BN",
    flag: "🇧🇳",
    keywords: ["BN", "BRN", "Brunei", "文莱", "汶萊"],
    area: "AREA_ASIA",
  },
  {
    cca2: "IN",
    flag: "🇮🇳",
    keywords: ["IN", "IND", "India", "印度", "孟买", "MFumbai", "Mumbai", "🇮🇳"],
    area: "AREA_ASIA",
  },
  {
    cca2: "NP",
    flag: "🇳🇵",
    keywords: ["NP", "NPL", "Nepal", "尼泊尔"],
    area: "AREA_ASIA",
  },
  {
    cca2: "BT",
    flag: "🇧🇹",
    keywords: ["BT", "BTN", "Bhutan", "不丹", "不丹王国"],
    area: "AREA_ASIA",
  },
  {
    cca2: "BD",
    flag: "🇧🇩",
    keywords: ["BD", "BGD", "Bangladesh", "孟加拉国", "孟加拉"],
    area: "AREA_ASIA",
  },
  {
    cca2: "LK",
    flag: "🇱🇰",
    keywords: ["LK", "LKA", "Sri Lanka", "斯里兰卡", "斯里蘭卡"],
    area: "AREA_ASIA",
  },
  {
    cca2: "PK",
    flag: "🇵🇰",
    keywords: ["PK", "PAK", "Pakistan", "巴基斯坦"],
    area: "AREA_ASIA",
  },
  {
    cca2: "AF",
    flag: "🇦🇫",
    keywords: ["AF", "AFG", "Afghanistan", "阿富汗"],
    area: "AREA_ASIA",
  },
  {
    cca2: "KG",
    flag: "🇰🇬",
    keywords: ["KG", "KGZ", "Kyrgyzstan", "吉尔吉斯斯坦"],
    area: "AREA_ASIA",
  },
  {
    cca2: "KZ",
    flag: "🇰🇿",
    keywords: ["KZ", "KAZ", "Kazakhstan", "哈萨克斯坦", "哈萨克"],
    area: "AREA_ASIA",
  },
  {
    cca2: "MN",
    flag: "🇲🇳",
    keywords: ["MN", "MNG", "Mongolia", "蒙古"],
    area: "AREA_ASIA",
  },
  {
    cca2: "KP",
    flag: "🇰🇵",
    keywords: ["KP", "PRK", "North Korea", "朝鲜"],
    area: "AREA_ASIA",
  },
  {
    cca2: "RU",
    flag: "🇷🇺",
    keywords: [
      "RU",
      "RUS",
      "Russia",
      "俄罗斯",
      "俄国",
      "俄羅斯",
      "伯力",
      "莫斯科",
      "圣彼得堡",
      "西伯利亚",
      "京俄",
      "杭俄",
      "廣俄",
      "滬俄",
      "广俄",
      "沪俄",
      "Moscow",
    ],
    area: "AREA_EUROPE",
  },
  {
    cca2: "IR",
    flag: "🇮🇷",
    keywords: ["IR", "IRN", "Iran", "伊朗"],
    area: "AREA_ASIA",
  },
  {
    cca2: "IQ",
    flag: "🇮🇶",
    keywords: ["IQ", "IRQ", "Iraq", "伊拉克", "巴格达", "Baghdad"],
    area: "AREA_ASIA",
  },
  {
    cca2: "AZ",
    flag: "🇦🇿",
    keywords: ["AZ", "AZE", "Azerbaijan", "阿塞拜疆"],
    area: "AREA_ASIA",
  },
  {
    cca2: "AM",
    flag: "🇦🇲",
    keywords: ["AM", "ARM", "Armenia", "亚美尼亚"],
    area: "AREA_ASIA",
  },
  {
    cca2: "GE",
    flag: "🇬🇪",
    keywords: ["GE", "GEO", "Georgia", "格鲁吉亚", "格魯吉亞"],
    area: "AREA_ASIA",
  },
  {
    cca2: "TR",
    flag: "🇹🇷",
    keywords: ["TR", "TUR", "Turkey", "土耳其", "伊斯坦布尔", "Istanbul", "🇹🇷"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "JO",
    flag: "🇯🇴",
    keywords: ["JO", "JOR", "Jordan", "约旦"],
    area: "AREA_ASIA",
  },
  {
    cca2: "IL",
    flag: "🇮🇱",
    keywords: ["IL", "ISR", "Israel", "以色列"],
    area: "AREA_ASIA",
  },
  {
    cca2: "SA",
    flag: "🇸🇦",
    keywords: ["SA", "SAU", "Saudi", "沙特阿拉伯", "沙特", "Riyadh", "利雅得"],
    area: "AREA_ASIA",
  },
  {
    cca2: "AE",
    flag: "🇦🇪",
    keywords: ["AE", "ARE", "United Arab Emirates", "阿联酋", "迪拜", "Dubai"],
    area: "AREA_ASIA",
  },
  {
    cca2: "QA",
    flag: "🇶🇦",
    keywords: ["QA", "QAT", "Qatar", "卡塔尔", "卡塔爾"],
    area: "AREA_ASIA",
  },
  {
    cca2: "BH",
    flag: "🇧🇭",
    keywords: ["BH", "BHR", "Bahrain", "巴林"],
    area: "AREA_ASIA",
  },
  {
    cca2: "OM",
    flag: "🇴🇲",
    keywords: ["OM", "OMN", "Oman", "阿曼", "马斯喀特"],
    area: "AREA_ASIA",
  },
  {
    cca2: "EG",
    flag: "🇪🇬",
    keywords: ["EG", "EGY", "Egypt", "埃及"],
    area: "AREA_AFRICA",
  },
  {
    cca2: "TN",
    flag: "🇹🇳",
    keywords: ["TN", "TUN", "Tunisia", "突尼斯"],
    area: "AREA_AFRICA",
  },
  {
    cca2: "DZ",
    flag: "🇩🇿",
    keywords: ["DZ", "DZA", "Algeria", "阿尔及利亚", "阿爾及利亞"],
    area: "AREA_AFRICA",
  },
  {
    cca2: "MA",
    flag: "🇲🇦",
    keywords: ["MA", "MAR", "Morocco", "摩洛哥"],
    area: "AREA_AFRICA",
  },
  {
    cca2: "NG",
    flag: "🇳🇬",
    keywords: ["NG", "NGA", "Nigeria", "尼日利亚", "尼日利亞", "🇳🇬"],
    area: "AREA_AFRICA",
  },
  {
    cca2: "KE",
    flag: "🇰🇪",
    keywords: ["KE", "KEN", "Kenya", "肯尼亚"],
    area: "AREA_AFRICA",
  },
  {
    cca2: "TG",
    flag: "🇹🇬",
    keywords: ["TG", "TGO", "Togo", "多哥", "洛美", "Lomé", "Lome"],
    area: "AREA_AFRICA",
  },
  {
    cca2: "ML",
    flag: "🇲🇱",
    keywords: ["ML", "MLI", "Mali", "马里"],
    area: "AREA_AFRICA",
  },
  {
    cca2: "ZA",
    flag: "🇿🇦",
    keywords: ["ZA", "ZAF", "JNB", "South Africa", "南非"],
    area: "AREA_AFRICA",
  },
  {
    cca2: "SO",
    flag: "🇸🇴",
    keywords: ["SO", "SOM", "Somalia", "索马里", "摩加迪沙", "Mogadishu"],
    area: "AREA_AFRICA",
  },
  {
    cca2: "ZW",
    flag: "🇿🇼",
    keywords: ["ZW", "ZWE", "Zimbabwe", "津巴布韦"],
    area: "AREA_AFRICA",
  },
  {
    cca2: "UA",
    flag: "🇺🇦",
    keywords: ["UA", "UKR", "Ukraine", "乌克兰", "烏克蘭", "🇺🇦"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "BY",
    flag: "🇧🇾",
    keywords: ["BY", "BLR", "Belarus", "白俄罗斯", "白俄"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "MD",
    flag: "🇲🇩",
    keywords: ["MD", "MDA", "Moldova", "摩尔多瓦", "摩爾多瓦"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "PL",
    flag: "🇵🇱",
    keywords: ["PL", "POL", "Poland", "波兰", "波蘭", "华沙", "Warsaw"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "LT",
    flag: "🇱🇹",
    keywords: ["LT", "LTU", "Lithuania", "立陶宛"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "LV",
    flag: "🇱🇻",
    keywords: ["LV", "LVA", "Latvia", "拉脱维亚", "Latvija"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "EE",
    flag: "🇪🇪",
    keywords: ["EE", "EST", "Estonia", "爱沙尼亚"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "FI",
    flag: "🇫🇮",
    keywords: ["FI", "FIN", "Finland", "芬兰", "芬蘭", "赫尔辛基"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "SE",
    flag: "🇸🇪",
    keywords: ["SE", "SWE", "Sweden", "瑞典", "斯德哥尔摩", "Stockholm"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "NO",
    flag: "🇳🇴",
    keywords: ["NO", "NOR", "Norway", "挪威"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "IS",
    flag: "🇮🇸",
    keywords: ["IS", "ISL", "Iceland", "冰岛", "冰島"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "DK",
    flag: "🇩🇰",
    keywords: ["DK", "DNK", "Denmark", "丹麦", "丹麥"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "DE",
    flag: "🇩🇪",
    keywords: [
      "DE",
      "DEU",
      "German",
      "德国",
      "德國",
      "京德",
      "滬德",
      "廣德",
      "沪德",
      "广德",
      "法兰克福",
      "Frankfurt",
      "德意志",
    ],
    area: "AREA_EUROPE",
  },
  {
    cca2: "NL",
    flag: "🇳🇱",
    keywords: [
      "NL",
      "NLD",
      "AMS",
      "Netherlands",
      "荷兰",
      "荷蘭",
      "尼德蘭",
      "阿姆斯特丹",
      "Amsterdam",
    ],
    area: "AREA_EUROPE",
  },
  {
    cca2: "BE",
    flag: "🇧🇪",
    keywords: ["BE", "BEL", "Belgium", "比利时", "比利時"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "LU",
    flag: "🇱🇺",
    keywords: ["LU", "LUX", "Luxembourg", "卢森堡"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "FR",
    flag: "🇫🇷",
    keywords: ["FR", "FRA", "France", "法国", "法國", "巴黎", "🇫🇷"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "GB",
    flag: "🇬🇧",
    keywords: [
      "GB",
      "GBR",
      "UK",
      "Great Britain",
      "英国",
      "England",
      "United Kingdom",
      "伦敦",
      "英",
      "London",
    ],
    area: "AREA_EUROPE",
  },
  {
    cca2: "IE",
    flag: "🇮🇪",
    keywords: ["IE", "IRL", "Ireland", "爱尔兰", "愛爾蘭", "都柏林"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "IM",
    flag: "🇮🇲",
    keywords: ["IM", "IMN", "Isle of Man", "马恩岛", "馬恩島"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "PT",
    flag: "🇵🇹",
    keywords: ["PT", "PRT", "Portugal", "葡萄牙"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "ES",
    flag: "🇪🇸",
    keywords: ["ES", "ESP", "Spain", "西班牙"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "AD",
    flag: "🇦🇩",
    keywords: ["AD", "AND", "Andorra", "安道尔"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "IT",
    flag: "🇮🇹",
    keywords: ["IT", "ITA", "Italy", "意大利", "義大利", "米兰", "Nachash"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "VA",
    flag: "🇻🇦",
    keywords: [
      "VA",
      "VAT",
      "Vatican",
      "Vatican City",
      "Holy See",
      "梵蒂冈",
      "梵蒂岡",
    ],
    area: "AREA_EUROPE",
  },
  {
    cca2: "MT",
    flag: "🇲🇹",
    keywords: ["MT", "MLT", "Malta", "马耳他"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "CH",
    flag: "🇨🇭",
    keywords: ["CH", "CHE", "Switzerland", "瑞士", "苏黎世", "Zurich"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "AT",
    flag: "🇦🇹",
    keywords: ["AT", "AUT", "Austria", "奥地利", "奧地利", "维也纳"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "HU",
    flag: "🇭🇺",
    keywords: ["HU", "HUN", "Hungary", "匈牙利"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "SK",
    flag: "🇸🇰",
    keywords: ["SK", "SVK", "Slovakia", "斯洛伐克"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "CZ",
    flag: "🇨🇿",
    keywords: ["CZ", "CZE", "Czechia", "捷克", "Czech", "Czech Republic"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "RO",
    flag: "🇷🇴",
    keywords: ["RO", "ROU", "Romania", "罗马尼亚"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "BG",
    flag: "🇧🇬",
    keywords: ["BG", "BGR", "Bulgaria", "保加利亚", "保加利亞"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "RS",
    flag: "🇷🇸",
    keywords: ["RS", "SRB", "Serbia", "塞尔维亚"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "MK",
    flag: "🇲🇰",
    keywords: ["MK", "MKD", "Macedonia", "马其顿", "馬其頓"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "AL",
    flag: "🇦🇱",
    keywords: ["AL", "ALB", "Albania", "阿尔巴尼亚", "阿爾巴尼亞"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "GR",
    flag: "🇬🇷",
    keywords: ["GR", "GRC", "Greece", "希腊", "希臘"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "SI",
    flag: "🇸🇮",
    keywords: ["SI", "SVN", "Slovenia", "斯洛文尼亚"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "HR",
    flag: "🇭🇷",
    keywords: ["HR", "HRV", "Croatia", "克罗地亚", "克羅地亞"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "BA",
    flag: "🇧🇦",
    keywords: ["BA", "BIH", "Bosnia and Herzegovina", "波黑共和国", "波黑"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "CY",
    flag: "🇨🇾",
    keywords: ["CY", "CYP", "Cyprus", "塞浦路斯"],
    area: "AREA_EUROPE",
  },
  {
    cca2: "AU",
    flag: "🇦🇺",
    keywords: [
      "AU",
      "AUS",
      "Australia",
      "澳大利亚",
      "澳洲",
      "墨尔本",
      "悉尼",
      "土澳",
      "京澳",
      "廣澳",
      "滬澳",
      "沪澳",
      "广澳",
      "Sydney",
    ],
    area: "AREA_OCEANIA",
  },
  {
    cca2: "NZ",
    flag: "🇳🇿",
    keywords: ["NZ", "NZL", "New Zealand", "新西兰", "新西蘭"],
    area: "AREA_OCEANIA",
  },
  {
    cca2: "PG",
    flag: "🇵🇬",
    keywords: ["PG", "PNG", "Papua New Guinea", "巴布亚新几内亚"],
    area: "AREA_OCEANIA",
  },
  {
    cca2: "WS",
    flag: "🇼🇸",
    keywords: ["WS", "WSM", "Samoa", "萨摩亚", "薩摩亞"],
    area: "AREA_OCEANIA",
  },
  {
    cca2: "GU",
    flag: "🇬🇺",
    keywords: ["GU", "GUM", "Guam", "关岛", "關島"],
    area: "AREA_OCEANIA",
  },
  {
    cca2: "MP",
    flag: "🇲🇵",
    keywords: [
      "MP",
      "MNP",
      "北马里亚纳",
      "Northern Mariana Islands",
      "Saipan",
      "塞班",
    ],
    area: "AREA_OCEANIA",
  },
  {
    cca2: "US",
    flag: "🇺🇸",
    keywords: [
      "US",
      "USA",
      "LAX",
      "SFO",
      "SJC",
      "United States",
      "美国",
      "America",
      "美",
      "京美",
      "波特兰",
      "达拉斯",
      "俄勒冈",
      "Oregon",
      "凤凰城",
      "费利蒙",
      "硅谷",
      "矽谷",
      "拉斯维加斯",
      "洛杉矶",
      "圣何塞",
      "圣克拉拉",
      "西雅图",
      "芝加哥",
      "沪美",
      "哥伦布",
      "纽约",
      "New York",
      "Los Angeles",
      "San Jose",
      "Sillicon Valley",
      "Michigan",
      "俄亥俄",
      "Ohio",
      "马纳萨斯",
      "Manassas",
      "弗吉尼亚",
      "Virginia",
      "🇺🇸",
      "🇺🇲",
    ],
    area: "AREA_NORTH_AMERICA",
  },
  {
    cca2: "CA",
    flag: "🇨🇦",
    keywords: [
      "CA",
      "CAN",
      "Canada",
      "加拿大",
      "蒙特利尔",
      "温哥华",
      "楓葉",
      "枫叶",
      "滑铁卢",
      "多伦多",
      "Waterloo",
      "Toronto",
    ],
    area: "AREA_NORTH_AMERICA",
  },
  {
    cca2: "MX",
    flag: "🇲🇽",
    keywords: ["MX", "MEX", "Mexico", "墨西哥"],
    area: "AREA_NORTH_AMERICA",
  },
  {
    cca2: "GT",
    flag: "🇬🇹",
    keywords: ["GT", "GTM", "Guatemala", "危地马拉"],
    area: "AREA_NORTH_AMERICA",
  },
  {
    cca2: "CR",
    flag: "🇨🇷",
    keywords: ["CR", "CRI", "Costa Rica", "哥斯达黎加"],
    area: "AREA_NORTH_AMERICA",
  },
  {
    cca2: "PA",
    flag: "🇵🇦",
    keywords: ["PA", "PAN", "Panama", "巴拿马"],
    area: "AREA_NORTH_AMERICA",
  },
  {
    cca2: "CO",
    flag: "🇨🇴",
    keywords: ["CO", "COL", "Colombia", "哥伦比亚"],
    area: "AREA_SOUTH_AMERICA",
  },
  {
    cca2: "VE",
    flag: "🇻🇪",
    keywords: ["VE", "VEN", "Venezuela", "委内瑞拉"],
    area: "AREA_SOUTH_AMERICA",
  },
  {
    cca2: "EC",
    flag: "🇪🇨",
    keywords: ["EC", "ECU", "Ecuador", "厄瓜多尔"],
    area: "AREA_SOUTH_AMERICA",
  },
  {
    cca2: "PE",
    flag: "🇵🇪",
    keywords: ["PE", "PER", "Peru", "秘鲁", "祕魯"],
    area: "AREA_SOUTH_AMERICA",
  },
  {
    cca2: "BO",
    flag: "🇧🇴",
    keywords: ["BO", "BOL", "Bolivia", "玻利维亚"],
    area: "AREA_SOUTH_AMERICA",
  },
  {
    cca2: "PY",
    flag: "🇵🇾",
    keywords: ["PY", "PRY", "Paraguay", "巴拉圭"],
    area: "AREA_SOUTH_AMERICA",
  },
  {
    cca2: "BR",
    flag: "🇧🇷",
    keywords: ["BR", "BRA", "Brazil", "巴西", "圣保罗"],
    area: "AREA_SOUTH_AMERICA",
  },
  {
    cca2: "CL",
    flag: "🇨🇱",
    keywords: ["CL", "CHL", "Chile", "智利"],
    area: "AREA_SOUTH_AMERICA",
  },
  {
    cca2: "AR",
    flag: "🇦🇷",
    keywords: ["AR", "ARG", "Argentina", "阿根廷"],
    area: "AREA_SOUTH_AMERICA",
  },
  {
    cca2: "UY",
    flag: "🇺🇾",
    keywords: ["UY", "URY", "Uruguay", "乌拉圭"],
    area: "AREA_SOUTH_AMERICA",
  },
  {
    cca2: "PR",
    flag: "🇵🇷",
    keywords: ["PR", "PRI", "Puerto Rico", "波多黎各"],
    area: "AREA_NORTH_AMERICA",
  },
  {
    cca2: "AW",
    flag: "🇦🇼",
    keywords: ["AW", "ABW", "Aruba", "阿鲁巴"],
    area: "AREA_NORTH_AMERICA",
  },
  {
    cca2: "AG",
    flag: "🇦🇬",
    keywords: ["AG", "ATG", "Antigua and Barbuda", "安提瓜和巴布达"],
    area: "AREA_NORTH_AMERICA",
  },
  {
    cca2: "RE",
    flag: "🇷🇪",
    keywords: ["RE", "REU", "Réunion", "留尼汪", "法属留尼汪"],
    area: "AREA_AFRICA",
  },
  {
    cca2: "GL",
    flag: "🇬🇱",
    keywords: ["GL", "GRL", "Greenland", "格陵兰岛", "格陵兰"],
    area: "AREA_NORTH_AMERICA",
  },
  {
    cca2: "AQ",
    flag: "🇦🇶",
    keywords: ["AQ", "ATA", "Antarctica", "南极洲", "南极"],
    area: "AREA_ANTARCTICA",
  },
];

const getFull = (proxy) => {
  if (!proxy) {
    return { cca2: "", flag: "", keywords: [], area: "", order: -1 };
  }
  const accurateLocation = proxy.properties?.location ?? "";
  const proxyName = proxy.name.toLowerCase();
  for (let i = 0; i < locationEntries.length; i++) {
    const entry = locationEntries[i];
    if (
      (accurateLocation && entry.cca2 === accurateLocation) ||
      proxyName.includes(entry.flag)
    ) {
      return { ...entry, order: i + 1 };
    }
  }
  // fallback
  for (let i = 0; i < locationEntries.length; i++) {
    const entry = locationEntries[i];
    if (
      entry.keywords.some(
        (keyword) =>
          keyword &&
          keyword !== "" &&
          proxyName.includes(keyword.toLowerCase()),
      )
    ) {
      return { ...entry, order: i + 1 };
    }
  }

  // not found
  return { cca2: "", flag: "", keywords: [], area: "", order: -1 };
};

const getLocation = (proxy) => getFull(proxy).cca2;
const getOrder = (proxy) => getFull(proxy).order;
const getArea = (proxy) => getFull(proxy).area;

const sortProxies = ({ proxies }) => {
  const emptyProviderKey = "_empty";
  const providerList = {};
  const finalProxies = [];

  // rename and merge proxies
  for (const proxy of proxies) {
    let providerName = emptyProviderKey;
    if (
      proxy.properties !== undefined &&
      proxy.properties.provider !== undefined
    ) {
      providerName = proxy.properties.provider;
      proxy.name = [providerName, proxy.name].join("/");
    }
    proxy.name = proxy.name.trim();

    providerList[providerName] = [...(providerList[providerName] ?? []), proxy];
  }

  Object.keys(providerList)
    .sort((a, b) => {
      if (a === emptyProviderKey) return b === emptyProviderKey ? 0 : -1;
      if (b === emptyProviderKey) return 0;
      else return a.localeCompare(b);
    })
    .map((providerName) => {
      const providerSet = providerList[providerName];
      providerSet.sort((a, b) => {
        const locationDiff = getOrder(a) - getOrder(b);
        if (locationDiff !== 0) return locationDiff;

        return a.name.localeCompare(b.name);
      });
      return providerSet;
    })
    .map((providerSet) => {
      finalProxies.push(...providerSet);
    });

  return finalProxies;
};

context.features = {
  ...(context.features ?? {}),
  location: {
    getFull,
    getLocation,
    getOrder,
    getArea,
    sortProxies,
    locationEntries,
  },
};
})();

// feature: transport
(() => {
const featureLocation = context.features.location;

const isTransport = ({ proxy }) => {
  return proxy?.properties?.transport || proxy?.properties?.transport?.is;
};

const isDestionation = ({ proxy }) => {
  return proxy?.properties?.destination || proxy?.properties?.destination?.is;
};

const completeTransport = ({ proxies, detourName, fallback }) => {
  if (detourName === undefined) {
    detourName = (cca2) => {
      if (cca2 === "") {
        return "🚀 Transport";
      }
      return "🚀 Transport (" + cca2 + ")";
    };
  } else if (typeof detourName === "string") {
    destinationProxies.map((p) => (p["dialer-proxy"] = detourName));
    return { [detourName]: transportProxies };
  } else if (typeof detourName != "function") {
    throw new Error(
      "wrong detoruName type, excepted: function,string. got: " +
        typeof detourName,
    );
  }

  const transportProxies = proxies.filter((proxy) => isTransport({ proxy }));
  const destinationProxies = proxies.filter((proxy) =>
    isDestionation({ proxy }),
  );

  const transportGroups = {};
  for (const tp of transportProxies) {
    const transportLocation = featureLocation.getLocation(tp);

    if (transportGroups[transportLocation] === undefined)
      transportGroups[transportLocation] = {
        use: false,
        name: detourName(transportLocation),
        proxies: [],
      };

    transportGroups[transportLocation].proxies.push(tp.name);
  }

  for (const dp of destinationProxies) {
    const destinationRequiredLocation = [];
    if (
      typeof dp.properties.destination !== "boolean" &&
      dp.properties.destination.require !== undefined
    ) {
      if (typeof dp.properties.destination.requires === "string")
        destinationRequiredLocation.push(dp.properties.destination.require);
      else if (Array.isArray(dp.properties.destination.require))
        destinationRequiredLocation.push(...dp.properties.destination.require);
    } else {
      const destinationLocation = featureLocation.getLocation(dp);
      if (destinationLocation !== "")
        destinationRequiredLocation.push(destinationLocation);

      if (typeof dp.properties.destination.suits === "string")
        destinationRequiredLocation.push(dp.properties.destination.suits);
      else if (Array.isArray(dp.properties.destination.suits))
        destinationRequiredLocation.push(...dp.properties.destination.suits);
      if (Array.isArray(fallback))
        destinationRequiredLocation.push(...fallback);
    }

    for (const loc of destinationRequiredLocation) {
      if ([loc] in transportGroups) {
        const selected = transportGroups[loc];
        selected.use = true;
        dp["dialer-proxy"] =
          selected.proxies.length > 1 ? selected.name : selected.proxies[0];
        break;
      }
    }
  }

  return transportGroups;
};

context.features = {
  ...(context.features ?? {}),
  transport: {
    completeTransport,
    isTransport,
    isDestionation,
  },
};
})();

context.const = {
  ...(context.const ?? {}),
  platform: "sing-box",
  outbound: {
    direct: "direct",
  },
  http_client: {
    direct: "http-direct",
  },
  dns: {
    direct: "dns-cn",
    ecs: "dns-ecs",
  },
};

const produce = (proxies = []) => {
  return JSON.parse(ProxyUtils.produce([...proxies], context.const.platform))
    .outbounds;
};

const produceEndpoint = (endpoints = []) => {
  return JSON.parse(
    ProxyUtils.produce(
      [
        ...endpoints.filter(
          (e) => e.type === "tailscale" || e.type === "wireguard",
        ),
      ],
      context.const.platform,
    ),
  ).endpoints;
};

const createSemverInfo = () => ({
  full: "",
  major: 0,
  minor: 0,
  patch: 0,
  prerelease: "",
  build: "",
  // sing-box
  alphaVersion: 0,
});

const parseSemver = (version) => {
  const defaultSemverInfo = createSemverInfo();

  if (typeof version !== "string" || version.trim() === "") {
    return defaultSemverInfo;
  }

  const semverRegex =
    /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/;

  const match = version.trim().match(semverRegex);
  if (!match) {
    return defaultSemverInfo;
  }

  const [full, major, minor, patch, prerelease = "", build = ""] = match;
  const alphaMatch = prerelease.match(/(?:^|\.)alpha\.(\d+)(?:\.|$)/);

  defaultSemverInfo.full = full;
  defaultSemverInfo.major = Number(major);
  defaultSemverInfo.minor = Number(minor);
  defaultSemverInfo.patch = Number(patch);
  defaultSemverInfo.prerelease = prerelease;
  defaultSemverInfo.build = build;
  defaultSemverInfo.alphaVersion = alphaMatch ? Number(alphaMatch[1]) : 0;
  return defaultSemverInfo;
};

const createUaInfo = () => ({
  SFM: false,
  SFI: false,
  SFT: false,
  SFA: false,
  SFD: false,
  SFW: false,
  SFL: false,
  isZhCN: false,
  isZhTW: false,
  isEnUS: false,
  isFa: false,
  isRu: false,
  version: parseSemver(),
});

const applyUaLanguage = (uaInfo, language) => {
  const normalized = language.trim().replaceAll("-", "_").toLowerCase();
  if (!normalized) return;

  if (/^zh(?:_|$)/.test(normalized)) {
    if (/(?:^|_)(?:hant|tw|hk|mo)(?:_|$)/.test(normalized)) {
      uaInfo.isZhTW = true;
    } else {
      uaInfo.isZhCN = true;
    }
  } else if (/^en(?:_|$)/.test(normalized)) {
    uaInfo.isEnUS = true;
  } else if (/^fa(?:_|$)/.test(normalized)) {
    uaInfo.isFa = true;
  } else if (/^ru(?:_|$)/.test(normalized)) {
    uaInfo.isRu = true;
  }
};

const uaLookup = (ua = "") => {
  if (typeof ua !== "string" || ua.trim() === "") {
    return undefined;
  }

  const defaultUaInfo = createUaInfo();
  const uaMatched = ua
    .trim()
    .match(/^([A-Z]{3})\s+\(sing-box\s+([^;()\s]+);\s*language\s+([^)]+)\)$/);

  if (
    !uaMatched ||
    !["SFM", "SFI", "SFT", "SFA", "SFD", "SFW", "SFL"].includes(uaMatched[1])
  ) {
    return defaultUaInfo;
  }

  const client = uaMatched[1];
  const version = parseSemver(uaMatched[2]);
  if (!version.full) {
    return defaultUaInfo;
  }

  defaultUaInfo[client] = true;
  defaultUaInfo.version = version;
  applyUaLanguage(defaultUaInfo, uaMatched[3]);

  return defaultUaInfo;
};

const findTun = (config = {}) => {
  const found = (config?.inbounds ?? []).filter((inb) => inb.type === "tun");
  return found.length > 0 ? found[0] : undefined;
};

const generateContext = async () => {
  const lookupQuery = (name) => {
    return $options?._req?.query?.[name];
  };

  const generated = {
    config: JSON.parse($files[0]),
    experimental: {},
    ua: uaLookup(
      $options?._req?.headers?.["user-agent"] ||
        $options?._req?.headers?.["User-Agent"] ||
        context.test?.ua,
    ),
  };

  if (lookupQuery("user") || context.test?.user) {
    const userID = lookupQuery("user") || context.test?.user || "";
    const produced = await produceArtifact({
      type: lookupQuery("prod_type") || "collection",
      name: userID,
      platform: "json",
      produceType: "internal",
    });
    generated.proxies = produced.filter((proxy) =>
      [
        "socks",
        "http",
        "ss",
        "vmess",
        "trojan",
        "naive",
        "hysteria",
        "hysteria2",
        "vless",
        "tuic",
        "anytls",
        "tor",
        "ssh",
        "snell",
      ].includes(proxy.type),
    );
    generated.endpoints = produced.filter((proxy) =>
      ["wireguard", "tailscale"].includes(proxy.type),
    );
  } else {
    generated.proxies = [];
  }

  (lookupQuery("experimental") || context.test?.experimental || "")
    .split(",")
    .map((fe) => {
      generated.experimental[fe] = true;
    });

  return generated;
};

const applySortAndCompability = ({ proxies = [], ...rest }) => {
  const sortedProxies = context.features.location.sortProxies({ proxies });

  // Notice heer , different platform has different name selector (tag or name)
  const names = produce(proxies).map((pp) => pp.tag);
  return {
    proxies: sortedProxies.filter((sp) => names.includes(sp.name)),
    ...rest,
  };
};

const applyTransport = ({
  proxies = [],
  config = {},
  experimental = {},
  ua = {},
  ...rest
}) => {
  const transportGroups = context.features.transport.completeTransport({
    proxies: proxies,
    detourName: (cca2) => {
      let defaultTransportName = "🚀 Transport";
      if (ua?.isZhCN) {
        defaultTransportName = "🚀 链式传输";
      } else if (ua?.isZhTW) {
        defaultTransportName = "🚀 鏈式傳輸";
      }
      if (!cca2) {
        return defaultTransportName;
      }
      return defaultTransportName + " (" + cca2 + ")";
    },
  });

  Object.keys(transportGroups).map((selectorName) => {
    const selected = transportGroups[selectorName];
    if (selected.use && selected.proxies.length > 1) {
      const transportGroup = {
        type: "selector",
        tag: selected.name,
        outbounds: [...selected.proxies],
      };
      config.outbounds = [transportGroup, ...config.outbounds];
    }
  });

  return {
    proxies: proxies.filter(
      (proxy) =>
        !context.features.transport.isDestionation({ proxy }) ||
        "dialer-proxy" in proxy,
    ),
    experimental,
    config,
    ua,
    ...rest,
  };
};

const applyGeoSiteGeoIP = ({ proxies = [], config = {}, ...rest }) => {
  const directIP = new Set();
  const directSite = new Set();
  for (const proxy of proxies) {
    if (proxy.server === undefined || proxy["dialer-proxy"]) {
      continue;
    }
    const serverAddr = proxy.server;
    if (serverAddr.includes(":")) {
      // IPv6
      directIP.add(serverAddr);
      continue;
    }

    const dots = serverAddr.split(".");
    if (dots.length === 4 && Number.isInteger(Number(dots[3])))
      directIP.add(serverAddr); // IPv4
    else directSite.add(serverAddr); // Domain
  }
  if (context.secret?.metadata?.ghproxy)
    directSite.add(context.secret?.metadata?.ghproxy);
  if (context.secret?.metadata?.subscribeURL)
    directSite.add(context.secret?.metadata?.subscribeURL);

  config.route?.rule_set?.map((rs) => {
    if (rs.tag === "@geosite-direct" && directSite.size > 0) {
      rs.rules[0].domain = [...(rs.rules[0].domain ?? []), ...[...directSite]];
    }

    if (rs.tag === "@geoip-direct" && directIP.size > 0) {
      rs.rules[0].ip_cidr = [
        ...(rs.rules[0].ip_cidr ?? []),
        ...[...directIP].map((ip) =>
          ip.includes(":") ? ip + "/128" : ip + "/32",
        ),
      ];
    }
  });

  return { proxies, config, ...rest };
};

const applyPushGroup = ({ proxies = [], config = {}, ...rest }) => {
  const out = proxies.filter(
    (proxy) =>
      proxy?.properties?.hidden === undefined || !proxy.properties.hidden,
  );
  config.outbounds
    .filter((p) => ["selector", "urltest"].includes(p.type))
    .map((selector) => {
      if (
        [
          "🙋 Select",
          "🔍 Google",
          "🐈 Git",
          "📦 Microsoft",
          "🎬 Entertainment",
          "📺 Youtube",
          "🤖 AI-Service",
          "🍎 Apple",
        ].includes(selector.tag)
      ) {
        selector.outbounds.push(...out.map((o) => o.name));
      } else if (["✈️ TelegramDC1(NA)"].includes(selector.tag)) {
        selector.outbounds.push(
          ...out
            .filter(
              (o) =>
                context.features.location.getArea(o) === "AREA_NORTH_AMERICA" ||
                context.features.location.getLocation(o) === "JP",
            )
            .map((o) => o.name),
        );
      } else if (["✈️ TelegramDC4(EU)"].includes(selector.tag)) {
        selector.outbounds.push(
          ...out
            .filter(
              (o) =>
                context.features.location.getArea(o) === "AREA_EUROPE" ||
                context.features.location.getLocation(o) === "HK",
            )
            .map((o) => o.name),
        );
      } else if (["✈️ TelegramDC5(AP)"].includes(selector.tag)) {
        selector.outbounds.push(
          ...out
            .filter((o) => context.features.location.getArea(o) === "AREA_ASIA")
            .map((o) => o.name),
        );
      }
    });
  return { proxies, config, ...rest };
};

const applyInternalDNSResolver = ({ config = {}, proxies = [], ...rest }) => {
  const isDomain = (addr) => {
    if (!addr || addr.includes(":")) return false; // empty or IPv6
    const dots = addr.split(".");
    // not an IPv4 literal => treat as domain
    return !(dots.length === 4 && Number.isInteger(Number(dots[3])));
  };

  // normalize proxy.properties.dns (string shorthand or object) into a
  // sing-box dns server object with a deterministic, dedupe-friendly tag.
  const buildSingDns = (proxy) => {
    const dns = proxy.properties.dns;
    const props = { type: "", server: "", path: "", port: 0 };
    if (typeof dns === "string") {
      props.type = "udp";
      props.server = dns;
    } else {
      props.type = dns.type ?? "";
      props.server = dns.server ?? "";
      props.path = dns.path ?? "";
      props.port = dns.port ?? 0;
    }

    let tag;
    if (proxy.properties?.provider)
      tag = "dns-for_provider_" + proxy.properties.provider;
    else
      tag =
        "dns-" +
        [props.type, props.server, props.path, props.port]
          .filter((v) => v)
          .join("_");

    const singDns = { type: props.type, server: props.server, tag };
    if (props.port) singDns.server_port = props.port;
    if ((props.type === "https" || props.type === "h3") && props.path !== "") {
      singDns.path = props.path;
    }

    // a dns server addressed by a domain needs a bootstrap resolver to
    // look up that address itself.
    if (isDomain(singDns.server)) {
      singDns.domain_resolver = { server: context.const.dns.direct };
    }

    return singDns;
  };

  // some airports ship their own dns. expose each as a sing-box dns server and
  // point the proxy's outbound.domain_resolver at it (sub-store passes
  // `_domain_resolver` through). the matching route-level dns.rules are added
  // later in post from the produced outbounds (see apply-internal-dns-rules).
  const dnsServers = {};

  for (const proxy of proxies) {
    if (!proxy.properties?.dns) continue;

    const singDns = buildSingDns(proxy);
    dnsServers[singDns.tag] = singDns;
    proxy._domain_resolver = { server: singDns.tag };
  }

  if (Object.keys(dnsServers).length === 0) {
    return { config, proxies, ...rest };
  }

  config.dns = config.dns ?? {};
  config.dns.servers = [
    ...(config.dns.servers ?? []),
    ...Object.values(dnsServers),
  ];

  return { config, proxies, ...rest };
};

const applyEndpoints = ({ config = {}, endpoints = [], ...rest }) => {
  const tailnetIPRanges = ["100.64.0.0/10", "fd7a:115c:a1e0::/48"];
  const endpoint = $options?._req?.query?.endpoint ?? "";

  // endpoint id generated by:
  // $ openssl rand -hex 16
  const endpointIDs = endpoint.split("_");
  if (endpointIDs.length === 0) return { config, endpoints: [], ...rest };

  const availableEndpoints = (endpoints ?? []).filter((ep) =>
    (endpointIDs ?? []).some((eid) => ep.properties?.endpoint?.id == eid),
  );

  if (availableEndpoints.length == 0) {
    // no endpoint available , so exclude tailnet ip range to tun configure.
    const tunInbound = findTun(config);
    if (tunInbound) {
      tunInbound.route_exclude_address = [
        ...(tunInbound.route_exclude_address ?? []),
        ...tailnetIPRanges,
      ];
    }

    return { config, endpoints, ...rest };
  }

  // tailscale endpoints
  const tailscaleEndpoints = availableEndpoints
    .filter((ep) => ep.type === "tailscale")
    .map((tsep) => {
      config.route = {
        ...(config.route ?? {}),
        rules: [
          {
            action: "route",
            outbound: tsep.name,
            preferred_by: tsep.name,
          },
          ...(config.route?.rules ?? []),
        ],
      };
      config.dns = {
        ...(config.dns ?? {}),
        servers: [
          ...(config.dns?.servers ?? []),
          {
            type: "tailscale",
            tag: "dns-" + tsep.name,
            endpoint: tsep.name,
            accept_search_domain: true,
          },
        ],
        rules: [
          {
            action: "evaluate",
            preferred_by: "dns-" + tsep.name,
            server: "dns-" + tsep.name,
            tag: "resolve-evaluate-tailscale-" + tsep.name,
          },
          {
            match_response: "resolve-evaluate-tailscale-" + tsep.name,
            ip_accept_any: true,
            action: "respond",
          },
          ...(config.dns?.rules ?? []),
        ],
      };
      return tsep;
    });

  // wireguard endpoints
  const wireguardEndpoints = availableEndpoints
    .filter((ep) => ep.type === "wireguard")
    .map((wgep) => {
      config.route = {
        ...(config.route ?? {}),
        rules: [
          {
            action: "route",
            outbound: wgep.name,
            preferred_by: wgep.name,
          },
          ...(config.route?.rules ?? []),
        ],
      };
      return wgep;
    });

  // openvpn-(client/server) , openconnect not supported

  return {
    config,
    endpoints: [...(tailscaleEndpoints ?? []), ...(wireguardEndpoints ?? [])],
    ...rest,
  };
};

const assembleConfig = ({
  config = {},
  proxies = [],
  endpoints = [],
  ...rest
}) => {
  return {
    ...rest,
    config: {
      ...config,
      outbounds: [...(config.outbounds ?? []), ...produce(proxies)],
      endpoints: [...(config.endpoints ?? []), ...produceEndpoint(endpoints)],
    },
  };
};

const applySyncDomainResolver = ({ config = {}, ...rest }) => {
  const isDomain = (addr) => {
    if (!addr || addr.includes(":")) return false; // empty or IPv6
    const dots = addr.split(".");
    // not an IPv4 literal => treat as domain
    return !(dots.length === 4 && Number.isInteger(Number(dots[3])));
  };

  const resolverTag = (dr) => (typeof dr === "string" ? dr : dr?.server);

  // walk the produced outbounds: any node whose server is a domain and that
  // carries a domain_resolver (set in pre via _domain_resolver) gets a
  // route-level dns.rule, so external resolution of that domain matches the
  // internal outbound resolution instead of diverging.
  const servedDomains = {};
  for (const outbound of config.outbounds ?? []) {
    if (!isDomain(outbound.server)) continue;

    let tag = resolverTag(outbound.domain_resolver);
    if (!tag) {
      const routeDefaultResolver = config?.route?.default_domain_resolver;
      if (routeDefaultResolver && typeof routeDefaultResolver === "string") {
        tag = routeDefaultResolver;
      } else if (
        routeDefaultResolver.server &&
        typeof routeDefaultResolver.server === "string"
      ) {
        tag = routeDefaultResolver.server;
      } else {
        tag = context.const.dns.direct;
      }
    }

    servedDomains[tag] = servedDomains[tag] ?? new Set();
    servedDomains[tag].add(outbound.server);
  }

  config.dns = {
    ...(config.dns ?? {}),
    rules: [
      ...(Object.entries(servedDomains).map(([server, domains]) => ({
        domain: [...domains],
        action: "route",
        server,
      })) ?? []),
      ...(config.dns.rules ?? []),
    ],
  };

  return { config, ...rest };
};

const applyBoostrapDirect = ({ config = {}, ...rest }) => {
  const ghproxy = context.secret?.metadata?.ghproxy ?? "hk.gh-proxy.org";
  const githubDomains = [
    "raw.githubusercontent.com",
    "github.com",
    "gist.githubusercontent.com",
  ];

  if (Array.isArray(config.route?.rule_set)) {
    config.route.rule_set.map((ruleset) => {
      if (
        ruleset.type === "remote" &&
        githubDomains.some((domain) =>
          ruleset.url.startsWith("https://" + domain),
        )
      ) {
        ruleset.url = `https://${ghproxy}/${ruleset.url}`;
        ruleset.http_client = context.const.http_client.direct;
      }
    });
  }
  if (
    config.experimental?.clash_api?.external_ui_download_url &&
    githubDomains.some((domain) =>
      config.experimental.clash_api.external_ui_download_url.startsWith(
        "https://" + domain,
      ),
    )
  ) {
    config.experimental.clash_api.external_ui_download_url = `https://${ghproxy}/${config.experimental.clash_api.external_ui_download_url}`;
    config.experimental.clash_api.external_ui_download_detour =
      context.const.outbound.direct;
  }

  return { config, ...rest };
};

const applyDnsEnhanced = ({ config = {}, experimental = {}, ...rest }) => {
  // client subnet
  const getClientIP = () => {
    const req = $options?._req;
    const headers = req?.headers ?? {};

    const ip =
      headers["cf-connecting-ip"] ||
      headers["true-client-ip"] ||
      headers["x-real-ip"] ||
      headers["x-forwarded-for"]?.split(",")[0]?.trim() ||
      req?.socket?.remoteAddress;
    return ip === undefined ? "114.114.114.114" : ip.trim();
  };

  const clientIP = getClientIP();
  for (const dnsRule of [...(config?.dns?.rules ?? [])])
    if (dnsRule.client_subnet === "") dnsRule.client_subnet = clientIP;

  // experimental h3
  if (experimental.dns_cn_use_h3 && Array.isArray(config?.dns?.servers))
    config.dns.servers.map((dns) => {
      if (dns.tag === context.const.dns.direct) dns.type = "h3";
    });

  // leak
  if (experimental.dns_leak_boost && Array.isArray(config?.dns?.rules)) {
    config.dns.rules.map((r) => {
      if (r.server === context.const.dns.ecs) {
        r.server = context.const.dns.direct;
        r.client_subnet = undefined;
      }
    });
  }

  // no local
  if (experimental.dns_local_use_dhcp && Array.isArray(config?.dns?.servers))
    config.dns.servers
      .filter((server) => server.type === "local")
      .forEach((server) => (server.type = "dhcp"));

  return { config, experimental, ...rest };
};

const applyPlatformSettings = ({ config = {}, ua = undefined, ...rest }) => {
  const ret = { config, ua, ...rest };
  if (ua === undefined) {
    return ret;
  }

  config?.inbounds
    ?.filter((inb) => inb.type === "tun")
    .map((tunInbound) => {
      if (ua.SFM) {
        // on macos , only set ipv6 dns address to fix the program
        // which read the /etc/resolv.conf as major dns resolver config.
        if (tunInbound.dns_address)
          tunInbound.dns_address = tunInbound.dns_address.filter((addr) =>
            addr.includes(":"),
          );

        // on macos , gvisor has better performance.
        tunInbound.stack = "gvisor";

        if (tunInbound.platform?.http_proxy?.enabled)
          tunInbound.platform.http_proxy.enabled = false;
      }
    });

  return ret;
};

const applySuperSecretSettingsFunc = () => {
  if (context.secret?.superSecretSettings) {
    return context.secret?.superSecretSettings;
  }

  return ({...rest}) => ({ ...rest });
};

const applyTranslation = ({ config = {}, ua = undefined, ...rest }) => {
  const ret = { config, ua, ...rest };

  const translations = {
    "🙋 Select": {
      zh_CN: "🙋 手动选择",
      zh_TW: "🙋 手動選擇",
      fa: "🙋 انتخاب دستی",
      ru: "🙋 Ручной выбор",
    },
    "🔍 Google": {
      zh_CN: "🔍 谷歌服务",
      zh_TW: "🔍 谷歌服務",
      fa: "🔍 سرویس‌های گوگل",
      ru: "🔍 Сервисы Google",
    },
    "🐈 Git": {
      zh_CN: "🐈 开发服务",
      zh_TW: "🐈 開發服務",
      fa: "🐈 سرویس‌های توسعه",
      ru: "🐈 Сервисы разработки",
    },
    "📦 Microsoft": {
      zh_CN: "📦 微软服务",
      zh_TW: "📦 微軟服務",
      fa: "📦 سرویس‌های مایکروسافت",
      ru: "📦 Сервисы Microsoft",
    },
    "📺 Youtube": {
      zh_CN: "📺 油管",
      zh_TW: "📺 油管",
      fa: "📺 یوتیوب",
      ru: "📺 YouTube",
    },
    "🎬 Entertainment": {
      zh_CN: "🎬 流媒体",
      zh_TW: "🎬 串流媒體",
      fa: "🎬 سرگرمی",
      ru: "🎬 Развлечения",
    },
    "🤖 AI-Service": {
      zh_CN: "🤖 AI服务",
      zh_TW: "🤖 AI 服務",
      fa: "🤖 سرویس هوش مصنوعی",
      ru: "🤖 Сервисы ИИ",
    },
    "🍎 Apple": {
      zh_CN: "🍎 苹果服务",
      zh_TW: "🍎 蘋果服務",
      fa: "🍎 سرویس‌های اپل",
      ru: "🍎 Сервисы Apple",
    },
    "✈️ TelegramDC1(NA)": {
      zh_CN: "✈️ 电报DC1 (北美)",
      zh_TW: "✈️ 電報DC1 (北美)",
      fa: "✈️ تلگرام DC1 (آمریکای شمالی)",
      ru: "✈️ Telegram DC1 (Северная Америка)",
    },
    "✈️ TelegramDC4(EU)": {
      zh_CN: "✈️ 电报DC4 (欧洲)",
      zh_TW: "✈️ 電報DC4 (歐洲)",
      fa: "✈️ تلگرام DC4 (اروپا)",
      ru: "✈️ Telegram DC4 (Европа)",
    },
    "✈️ TelegramDC5(AP)": {
      zh_CN: "✈️ 电报DC5 (亚太)",
      zh_TW: "✈️ 電報DC5 (亞太)",
      fa: "✈️ تلگرام DC5 (آسیا-اقیانوسیه)",
      ru: "✈️ Telegram DC5 (Азиатско-Тихоокеанский регион)",
    },
  };

  let translation;
  if (ua?.isZhCN) {
    translation = "zh_CN";
  } else if (ua?.isZhTW) {
    translation = "zh_TW";
  } else if (ua?.isEnUS) {
    translation = "en_US";
  } else if (ua?.isFa) {
    translation = "fa";
  } else if (ua?.isRu) {
    translation = "ru";
  }

  if (!config || !translation) {
    return ret;
  }

  let jsonConfig = JSON.stringify(config);
  Object.entries(translations).map(([raw, localized]) => {
    const target = localized[translation] ?? raw;
    jsonConfig = jsonConfig.replaceAll(raw, target);
  });

  return { config: JSON.parse(jsonConfig), ua, ...rest };
};

const emitContent = ({ config = {} }) => {
  $content = JSON.stringify(config);
  return { config };
};

await generateContext()
  .then(applySortAndCompability)
  .then(applyTransport)
  .then(applyGeoSiteGeoIP)
  .then(applyPushGroup)
  .then(applyInternalDNSResolver)
  .then(applyEndpoints)
  .then(assembleConfig)
  .then(applySyncDomainResolver)
  .then(applyBoostrapDirect)
  .then(applyDnsEnhanced)
  .then(applyPlatformSettings)
  .then(applySuperSecretSettingsFunc())
  .then(applyTranslation)
  .then(emitContent);
